%% Correlations of EEG with neuropsychology/clinical/psychoacoustics/struct

% I want white backgrounds
set(0,'defaultfigurecolor',[1 1 1]); 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% MODIFY THIS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
group_to_plot = 'FE'; % 'FE', 'C', 'ALL' % string
gavr_name = 'GAVR'; % Stats based on subjects from this average
Quiet_treshold_type = 'Original'; % 'ChrLab' OR 'Original'
plot_only_significant_ones = 1; 
p_threshold = 0.1;
% GAVR_12C_vs_10FE
channel_data = 'Cz'; % 'Cz', 'cluster' string
Brain_signal = 'FFR'; % 'FFR' 'LLR'
FFR_section = 'Constant'; % If FFR, specify: % 'Transient', 'Constant', 'Total'
FFR_freq = 'high'; % 'low', 'medium', 'high'
% Which scales (matching vars, neuropsychology, clinical, psychoacoustics)
Correlate_with = 'psychoacoustics'; 
% 'matching_vars', 'neuropsychology', 'clinical', clinical_composite, 
% duration_of_illness, medication 'psychoacoustics','psychoacoustics_average'
specific_brain_signal = {}; % Empty ({}) by default: e.g. 'F0_SNR_low_Constant' (will cancel previous) % 'STR_xcorr_high','neur_lag_high'
% 'FD_average','MD_average'
specific_correlate_with = {}; % Empty ({}) by default: e.g. 'ROLEHIGH' (will cancel previous)
% 'FD_average','ITD_average','QT_L_average','QT_R_average','SIND','MD_average'
% 'PANSSP_RS',...
%     'PANSS_Affect','PANSS_Disorg','PANSS_Negative','PANSS_Positive','PANSS_Resistance',...
%     'BPRS_Total','BPRS_Positive','BPRS_Negative','BPRS_DeprAnx','BPRS_ActMania','BPRS_HostSusp'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% All variables
if strcmp(Quiet_treshold_type,'ChrLab')  
header_measures = {'Subj','Group',...
    'RMS_low_Baseline','RMS_low_Transient','RMS_low_Constant','RMS_low_Total',...
    'AMP_SNR_low_Transient','AMP_SNR_low_Constant','AMP_SNR_low_Total',...
    'STR_xcorr_low','neur_lag_low',...
    'pitch_err_low','pitch_str_low',...
    'F0_peak_low_Baseline','F0_peak_low_Transient','F0_peak_low_Constant','F0_peak_low_Total',...
    'F0_SNR_low_Baseline','F0_SNR_low_Transient','F0_SNR_low_Constant','F0_SNR_low_Total',...
    'RMS_medium_Baseline','RMS_medium_Transient','RMS_medium_Constant','RMS_medium_Total',...
    'AMP_SNR_medium_Transient','AMP_SNR_medium_Constant','AMP_SNR_medium_Total',...
    'STR_xcorr_medium','neur_lag_medium',...
    'pitch_err_medium','pitch_str_medium',...
    'F0_peak_medium_Baseline','F0_peak_medium_Transient','F0_peak_medium_Constant','F0_peak_medium_Total',...
    'F0_SNR_medium_Baseline','F0_SNR_medium_Transient','F0_SNR_medium_Constant','F0_SNR_medium_Total',...
    'RMS_high_Baseline','RMS_high_Transient','RMS_high_Constant','RMS_high_Total',...
    'AMP_SNR_high_Transient','AMP_SNR_high_Constant','AMP_SNR_high_Total',...
    'STR_xcorr_high','neur_lag_high',...
    'pitch_err_high','pitch_str_high',...
    'F0_peak_high_Baseline','F0_peak_high_Transient','F0_peak_high_Constant','F0_peak_high_Total',...
    'F0_SNR_high_Baseline','F0_SNR_high_Transient','F0_SNR_high_Constant','F0_SNR_high_Total',...
    'LLR_400ms_P50','LLR_400ms_N1','LLR_400ms_P2',...
    'LLR_1s_P50','LLR_1s_N1','LLR_1s_P2',...
    'AGE','SEX','VOCAB_TS','PSES',... % FOR MATCHING
    'OVERALLTSCR','MATRIX_TS','FULL2IQ',... % NEUROPSYCHO TESTS
    'SPEEDTSCR', 'ATT_VIGTSCR', 'WMTSCR', 'VERBTSCR', 'VISTSCR', 'RPSTSCR', 'SOCCOGTSCR','SANITM',...
    'SAPITM', 'ROLECURR', 'ROLELOW', 'ROLEHIGH', 'SOCIALCURR', 'SOCIALLOW', 'SOCIALHIGH','SFS_WITHDRAW_RS',...
    'SFS_INTERACT_RS', 'SFS_RECREAT_RS', 'SFS_OCCUP_RS', 'SFS_IND_PERF_RS', 'SFS_IND_COMP_RS','SFS_PROSOC_RS',...
    'PANSSP_RS', 'PANSSN_RS', 'PANSST_RS','PSYRATS_AUD_HALL', 'PSYRATS_DELUSIONS',... % CLINICAL TESTS
    'PANSS_Affect','PANSS_Disorg','PANSS_Negative','PANSS_Positive','PANSS_Resistance',... % COMPOSITE SCORES
    'P3','SANSSAPS_Level7_AudHall','SANSSAPS_Level4_RealityDis','BPRS_Positive',...
    'QT_L_125Hz', 'QT_L_250Hz', 'QT_L_500Hz', 'QT_L_1000Hz', 'QT_L_2000Hz', 'QT_L_4000Hz',... % PSYCHOACOUSTICS
    'QT_L_8000Hz','QT_R_125Hz', 'QT_R_250Hz', 'QT_R_500Hz', 'QT_R_1000Hz', 'QT_R_2000Hz', 'QT_R_4000Hz',...
    'QT_R_8000Hz','FD_250Hz', 'FD_1000Hz', 'FD_4000Hz', 'ITD_500Hz', 'ITD_1000Hz', 'ITD_2000Hz', 'ITD_4000Hz',...
    'MD_4Hz', 'MD_16Hz', 'MD_64Hz', 'SIND',...
    'QT_L_average','QT_R_average','FD_average','ITD_average',...
    'DAYS_SINCE_PRDM','DAYS_SINCE_1STEP','DAYS_SINCE_DISOR',...
    'SFS_Mean', 'HVLTRRAWSUM', 'HVLTRTSCR', 'FLUENRAW', 'FLUENTSCR'}; % DURATION OF ILLNESS (IN DAYS)
elseif strcmp(Quiet_treshold_type,'Original')  
    header_measures = {'Subj','Group',...
    'RMS_low_Baseline','RMS_low_Transient','RMS_low_Constant','RMS_low_Total',...
    'AMP_SNR_low_Transient','AMP_SNR_low_Constant','AMP_SNR_low_Total',...
    'STR_xcorr_low','neur_lag_low',...
    'pitch_err_low','pitch_str_low',...
    'F0_peak_low_Baseline','F0_peak_low_Transient','F0_peak_low_Constant','F0_peak_low_Total',...
    'F0_SNR_low_Baseline','F0_SNR_low_Transient','F0_SNR_low_Constant','F0_SNR_low_Total',...
    'RMS_medium_Baseline','RMS_medium_Transient','RMS_medium_Constant','RMS_medium_Total',...
    'AMP_SNR_medium_Transient','AMP_SNR_medium_Constant','AMP_SNR_medium_Total',...
    'STR_xcorr_medium','neur_lag_medium',...
    'pitch_err_medium','pitch_str_medium',...
    'F0_peak_medium_Baseline','F0_peak_medium_Transient','F0_peak_medium_Constant','F0_peak_medium_Total',...
    'F0_SNR_medium_Baseline','F0_SNR_medium_Transient','F0_SNR_medium_Constant','F0_SNR_medium_Total',...
    'RMS_high_Baseline','RMS_high_Transient','RMS_high_Constant','RMS_high_Total',...
    'AMP_SNR_high_Transient','AMP_SNR_high_Constant','AMP_SNR_high_Total',...
    'STR_xcorr_high','neur_lag_high',...
    'pitch_err_high','pitch_str_high',...
    'F0_peak_high_Baseline','F0_peak_high_Transient','F0_peak_high_Constant','F0_peak_high_Total',...
    'F0_SNR_high_Baseline','F0_SNR_high_Transient','F0_SNR_high_Constant','F0_SNR_high_Total',...
    'LLR_400ms_P50','LLR_400ms_N1','LLR_400ms_P2',...
    'LLR_1s_P50','LLR_1s_N1','LLR_1s_P2',...
    'AGE','SEX','VOCAB_TS','PSES',... % FOR MATCHING
    'OVERALLTSCR','MATRIX_TS','FULL2IQ',... % NEUROPSYCHO TESTS
    'SPEEDTSCR', 'ATT_VIGTSCR', 'WMTSCR', 'VERBTSCR', 'VISTSCR', 'RPSTSCR', 'SOCCOGTSCR','SANITM',...
    'SAPITM', 'ROLECURR', 'ROLELOW', 'ROLEHIGH', 'SOCIALCURR', 'SOCIALLOW', 'SOCIALHIGH','SFS_WITHDRAW_RS',...
    'SFS_INTERACT_RS', 'SFS_RECREAT_RS', 'SFS_OCCUP_RS', 'SFS_IND_PERF_RS', 'SFS_IND_COMP_RS','SFS_PROSOC_RS',...
    'PANSSP_RS', 'PANSSN_RS', 'PANSST_RS','PSYRATS_AUD_HALL', 'PSYRATS_DELUSIONS',... % CLINICAL TESTS
    'PANSS_Affect','PANSS_Disorg','PANSS_Negative','PANSS_Positive','PANSS_Resistance',... % COMPOSITE SCORES
    'P3','SANSSAPS_Level7_AudHall','SANSSAPS_Level4_RealityDis','BPRS_Positive',...
    'QuiT_L_1000', 'QuiT_L_1500', 'QuiT_L_2000', 'QuiT_L_3000', 'QuiT_L_4000',... % PSYCHOACOUSTICS
    'QuiT_R_1000', 'QuiT_R_1500', 'QuiT_R_2000', 'QuiT_R_3000', 'QuiT_R_4000',...
    'FD_250Hz', 'FD_1000Hz', 'FD_4000Hz', 'ITD_500Hz', 'ITD_1000Hz', 'ITD_2000Hz', 'ITD_4000Hz',...
    'MD_4Hz', 'MD_16Hz', 'MD_64Hz', 'SIND',...
    'QT_L_average','QT_R_average','FD_average','ITD_average',...
    'DAYS_SINCE_PRDM','DAYS_SINCE_1STEP','DAYS_SINCE_DISOR',...
    'SFS_Mean', 'HVLTRRAWSUM', 'HVLTRTSCR', 'FLUENRAW', 'FLUENTSCR'}; % DURATION OF ILLNESS (IN DAYS)
end

% Define Brain measures
if isempty(specific_brain_signal)
if strcmp(Brain_signal,'FFR')
% Define FFR measures
    if strcmp(FFR_freq, 'low') && strcmp(FFR_section, 'Transient')
        corr_A = {'RMS_low_Transient','AMP_SNR_low_Transient',...
            'STR_xcorr_low','neur_lag_low',...
            'F0_peak_low_Transient','F0_SNR_low_Transient','STR_xcorr_low','neur_lag_low'};
        % 'pitch_err_low','pitch_str_low'
    elseif strcmp(FFR_freq, 'low') && strcmp(FFR_section, 'Constant')
        corr_A = {'RMS_low_Constant','AMP_SNR_low_Constant',...
            'STR_xcorr_low','neur_lag_low',...
            'F0_peak_low_Constant','F0_SNR_low_Constant','STR_xcorr_low','neur_lag_low'};
        % 'pitch_err_low','pitch_str_low'
    elseif strcmp(FFR_freq, 'low') && strcmp(FFR_section, 'Total')
        corr_A = {'RMS_low_Total','AMP_SNR_low_Total',...
            'STR_xcorr_low','neur_lag_low',...
            'F0_peak_low_Total','F0_SNR_low_Total','STR_xcorr_low','neur_lag_low'};
        % 'pitch_err_low','pitch_str_low'
    elseif strcmp(FFR_freq, 'medium') && strcmp(FFR_section, 'Transient')
        corr_A = {'RMS_medium_Transient','AMP_SNR_medium_Transient',...
            'STR_xcorr_medium','neur_lag_medium',...
            'F0_peak_medium_Transient','F0_SNR_medium_Transient','STR_xcorr_medium','neur_lag_medium'};
        % 'pitch_err_medium','pitch_str_medium'
    elseif strcmp(FFR_freq, 'medium') && strcmp(FFR_section, 'Constant')
        corr_A = {'RMS_medium_Constant','AMP_SNR_medium_Constant',...
            'STR_xcorr_medium','neur_lag_medium',...
            'F0_peak_medium_Constant','F0_SNR_medium_Constant','STR_xcorr_medium','neur_lag_medium'};
        % 'pitch_err_medium','pitch_str_medium'
    elseif strcmp(FFR_freq, 'medium') && strcmp(FFR_section, 'Total')
        corr_A = {'RMS_medium_Total','AMP_SNR_medium_Total',...
            'STR_xcorr_medium','neur_lag_medium',...
            'F0_peak_medium_Total','F0_SNR_medium_Total','STR_xcorr_medium','neur_lag_medium'};
        % 'pitch_err_medium','pitch_str_medium'
    elseif strcmp(FFR_freq, 'high') && strcmp(FFR_section, 'Transient')
        corr_A = {'RMS_high_Transient','AMP_SNR_high_Transient',...
            'STR_xcorr_high','neur_lag_high',...
            'F0_peak_high_Transient','F0_SNR_high_Transient','STR_xcorr_high','neur_lag_high'};
        % 'pitch_err_high','pitch_str_high'
    elseif strcmp(FFR_freq, 'high') && strcmp(FFR_section, 'Constant')
        corr_A = {'RMS_high_Constant','AMP_SNR_high_Constant',...
            'STR_xcorr_high','neur_lag_high',...
            'F0_peak_high_Constant','F0_SNR_high_Constant','STR_xcorr_high','neur_lag_high'};
        % 'pitch_err_high','pitch_str_high'
    elseif strcmp(FFR_freq, 'high') && strcmp(FFR_section, 'Total')
        corr_A = {'RMS_high_Total','AMP_SNR_high_Total',...
            'STR_xcorr_high','neur_lag_high',...
            'F0_peak_high_Total','F0_SNR_high_Total','STR_xcorr_high','neur_lag_high'};
        % 'pitch_err_high','pitch_str_high'
    end
elseif strcmp(Brain_signal,'LLR')
    % Define LLR measures
    corr_A = {'LLR_400ms_P50','LLR_400ms_N1','LLR_400ms_P2',...
    'LLR_1s_P50','LLR_1s_N1','LLR_1s_P2'};
end
else
    corr_A = specific_brain_signal;
end

% Define what to correlate with 
if isempty(specific_correlate_with)
if strcmp(Correlate_with,'matching_vars')
    corr_B = {'AGE','SEX','VOCAB_TS','PSES'};
elseif strcmp(Correlate_with,'neuropsychology')
    corr_B = {'YRSED','OVERALLTSCR','MATRIX_TS','FULL2IQ','SPEEDTSCR',... % NEUROPSYCHO TESTS
    'ATT_VIGTSCR', 'WMTSCR', 'VERBTSCR', 'VISTSCR', 'RPSTSCR', 'SOCCOGTSCR','SANITM', 'SAPITM', 'ROLECURR',...
    'ROLELOW', 'ROLEHIGH', 'SOCIALCURR', 'SOCIALLOW', 'SOCIALHIGH','SFS_WITHDRAW_RS', 'SFS_INTERACT_RS',...
    'SFS_RECREAT_RS', 'SFS_OCCUP_RS', 'SFS_IND_PERF_RS', 'SFS_IND_COMP_RS','SFS_PROSOC_RS',...
    'SFS_Mean', 'HVLTRRAWSUM', 'HVLTRTSCR', 'FLUENRAW', 'FLUENTSCR'};
elseif strcmp(Correlate_with,'clinical') % Clinical
    corr_B = {'PANSSP_RS','PANSSN_RS', 'PANSST_RS','PSYRATS_AUD_HALL', 'PSYRATS_DELUSIONS'};    
elseif strcmp(Correlate_with,'clinical_composite') % Clinical composite
    corr_B = {'SANSSAPS_Level7_AudHall','SANSSAPS_Level7_UnusPercBeh','SANSSAPS_Level7_Delusions',... % COMPOSITE SCORES
    'SANSSAPS_Level7_ThDis','SANSSAPS_Level7_Inattention','SANSSAPS_Level7_Inexpress','SANSSAPS_Level7_Apathy',...
    'SANSSAPS_Level4_RealityDis','SANSSAPS_Level4_ThDis','SANSSAPS_Level4_Inexpress','SANSSAPS_Level4_Apathy',...
    'PANSS_Affect','PANSS_Disorg','PANSS_Negative','PANSS_Positive','PANSS_Resistance',...
    'BPRS_Total','BPRS_Positive','BPRS_Negative','BPRS_DeprAnx','BPRS_ActMania','BPRS_HostSusp'};
elseif strcmp(Correlate_with,'duration_of_illness') % Duration of illness (in days)
    corr_B = {'DAYS_SINCE_PRDM','DAYS_SINCE_1STEP','DAYS_SINCE_DISOR',...
    'DUP', 'PSYCH2SCAN', 'MED2SCAN'};
elseif strcmp(Correlate_with,'medication') % Medication load
    corr_B = {'CPZ_equivalent'};
elseif strcmp(Correlate_with,'psychoacoustics')
    if strcmp(Quiet_treshold_type,'ChrLab')  
        corr_B = {'QT_L_125Hz', 'QT_L_250Hz', 'QT_L_500Hz', 'QT_L_1000Hz', 'QT_L_2000Hz', 'QT_L_4000Hz',... 
    'QT_L_8000Hz','QT_R_125Hz', 'QT_R_250Hz', 'QT_R_500Hz', 'QT_R_1000Hz', 'QT_R_2000Hz', 'QT_R_4000Hz',...
    'QT_R_8000Hz','FD_250Hz', 'FD_1000Hz', 'FD_4000Hz', 'ITD_500Hz', 'ITD_1000Hz', 'ITD_2000Hz', 'ITD_4000Hz',...
    'MD_4Hz','MD_16Hz','MD_64Hz','SIND'};
    elseif strcmp(Quiet_treshold_type,'Original')  
        corr_B = {'QuiT_L_1000', 'QuiT_L_1500', 'QuiT_L_2000', 'QuiT_L_3000', 'QuiT_L_4000',...
    'QuiT_R_1000', 'QuiT_R_1500', 'QuiT_R_2000', 'QuiT_R_3000', 'QuiT_R_4000',...
    'FD_250Hz', 'FD_1000Hz', 'FD_4000Hz', 'ITD_500Hz', 'ITD_1000Hz', 'ITD_2000Hz', 'ITD_4000Hz',...
    'MD_4Hz','MD_16Hz','MD_64Hz','SIND'};
    end
elseif strcmp(Correlate_with,'psychoacoustics_average')
    corr_B = {'QT_L_average','QT_R_average','FD_average','MD_average','ITD_average','SIND'};
end
else
    corr_B = specific_correlate_with;
end

% Prepare for loop and load Matrix
pvals = []; p_vals_pos = 1; header_pvals = {};
load([root_dir '/Statistics/' gavr_name '/Mega_variable_FFR_' channel_data '.mat']);

% Adjust Matrix to contain FE or C
if strcmp(group_to_plot,'FE')
    % Find FE subjects
    warning('Selecting FE only...');
    group_indices = find(strcmp(Mega_variable_FFR(:,2),'FE'));
    group_indices = [1 group_indices']; % Add header column
    Mega_variable_FFR = Mega_variable_FFR([group_indices],:);
    color_group = [255 0 0];
elseif strcmp(group_to_plot,'C')
    % Find FE subjects
    warning('Selecting C only...');
    group_indices = find(strcmp(Mega_variable_FFR(:,2),'C'));
    group_indices = [1 group_indices']; % Add header column
    Mega_variable_FFR = Mega_variable_FFR([group_indices],:);
    color_group = [0 0 0];
elseif strcmp(group_to_plot,'ALL')
    warning('Selecting FE and Controls...');
    color_group = [50 50 50];
end

% Now correlate
for bm = 1:length(corr_A) % Brain measure
pos_measu = find(strcmp(Mega_variable_FFR(1,:),corr_A{bm}));
for i = 1:length(corr_B)
    pos_col = find(strcmp(Mega_variable_FFR(1,:),corr_B{i}));
    Cell_corr = Mega_variable_FFR(:,[pos_measu,pos_col]);
    % Correct for "[]" cells
    empty_cells = find(cellfun(@isempty,Cell_corr(:,:))); % Before: Cell_corr(:,:)
    Cell_corr(empty_cells) = num2cell(NaN); % Before: Cell_corr(empty_cells,2)
    Table_corr = cell2table(Cell_corr(2:end,:));
    Table_corr.Properties.VariableNames = Cell_corr(1,:);
    try
        [R, PValue] = corrplot(Table_corr,'type','Spearman','testR', 'on');
        if plot_only_significant_ones == 1
            if PValue(2,1) >= p_threshold
                fig = gcf;
                close(fig);
                continue;
            end
        end
        pvals(p_vals_pos) = PValue(2,1);
        table_columns = Table_corr.Properties.VariableNames;
        header_pvals{p_vals_pos} = [table_columns{1} '_&_' table_columns{2}];
        p_vals_pos = p_vals_pos + 1;
        % Check n included in this correlation
        Test_NaN = Table_corr{:,:}; % Convert table to Matrix
        [NaNrows, ~] = find(isnan(Test_NaN)); % Check rows with NaN
        n_corr = (size(Test_NaN,1)) - length(NaNrows); % determine n based on previous info
        % Delete all but the convenient subplot
        h = get(gcf, 'children');
        % get true x labels first (weird issue with corrplot)
        true_x_axis_labels = get(h(1), 'YTick'); 
        delete(h(1:5));
        % Adjust labels
        current_title = [corr_A{bm} ' (n = ' num2str(n_corr) ' ' group_to_plot ')'];
        current_title = strrep(current_title,'_',' ');
        xlabel(current_title,'Color','k');
        current_title = corr_B{i};
        current_title = strrep(current_title,'_',' ');
        ylabel(current_title,'Color','k');
        % Adjust x axis labels (weird issue with corrplot)
        xticklabels(true_x_axis_labels)
        % Adjust color and style
        hline = findobj(gcf, 'type', 'line');
        set(hline(1),'Color','k') % Line fit
        set(hline(2),'Color',color_group/256) % Actual dots
        set(hline(2),'LineWidt',3) % Actual dots
    catch
        p_vals_pos = p_vals_pos + 1;
        continue;
    end
end
end

% Define pvals variable to back-track the exact pvalues if needed
PVALS_STRING = {};
PVALS_STRING(1,:) = header_pvals;
PVALS_STRING(2,:) = num2cell(pvals);
PVALS_STRING = PVALS_STRING';
